spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
  datasource:
    url: jdbc:mysql://localhost:3306/xpef?serverTimezone=GMT%2B8
    username: xpefadmin
    password: xpef2021
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*
